// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StajyerTakip.DAL;

#nullable disable

namespace StajyerTakip.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806081933_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Beceri", b =>
                {
                    b.Property<int>("BeceriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BeceriId"));

                    b.Property<string>("BeceriAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BeceriKategoriId")
                        .HasColumnType("integer");

                    b.HasKey("BeceriId");

                    b.HasIndex("BeceriKategoriId");

                    b.ToTable("Beceriler");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.BeceriKategori", b =>
                {
                    b.Property<int>("BeceriKategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BeceriKategoriId"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BeceriKategoriId");

                    b.ToTable("BeceriKategorileri");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Degerlendirme", b =>
                {
                    b.Property<int>("DegerlendirmeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DegerlendirmeId"));

                    b.Property<int>("DegerlendirenId")
                        .HasColumnType("integer");

                    b.Property<int>("KriterId")
                        .HasColumnType("integer");

                    b.Property<short>("Puan")
                        .HasColumnType("smallint");

                    b.Property<int>("StajyerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DegerlendirmeId");

                    b.HasIndex("DegerlendirenId");

                    b.HasIndex("KriterId");

                    b.HasIndex("StajyerId");

                    b.ToTable("Degerlendirmeler");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.DegerlendirmeKriteri", b =>
                {
                    b.Property<int>("KriterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KriterId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("KriterAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("KriterId");

                    b.ToTable("DegerlendirmeKriterleri");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Departman", b =>
                {
                    b.Property<int>("DepartmanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmanId"));

                    b.Property<string>("DepartmanAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DepartmanId");

                    b.ToTable("Departmanlar");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Dosya", b =>
                {
                    b.Property<int>("DosyaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DosyaId"));

                    b.Property<int?>("BoyutKb")
                        .HasColumnType("integer");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DosyaKategoriId")
                        .HasColumnType("integer");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StajyerId")
                        .HasColumnType("integer");

                    b.Property<string>("Uzanti")
                        .HasColumnType("text");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("YukleyenId")
                        .HasColumnType("integer");

                    b.HasKey("DosyaId");

                    b.HasIndex("DosyaKategoriId");

                    b.HasIndex("StajyerId");

                    b.HasIndex("YukleyenId");

                    b.ToTable("Dosyalar");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.DosyaKategori", b =>
                {
                    b.Property<int>("DosyaKategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DosyaKategoriId"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DosyaKategoriId");

                    b.ToTable("DosyaKategorileri");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<int?>("DepartmanId")
                        .HasColumnType("integer");

                    b.Property<string>("Eposta")
                        .HasColumnType("text");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("SifreHash")
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("KullaniciId");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("RolId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Link", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LinkId"));

                    b.Property<string>("LinkTuru")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StajyerId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LinkId");

                    b.HasIndex("StajyerId");

                    b.ToTable("Linkler");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Modul", b =>
                {
                    b.Property<int>("ModulId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModulId"));

                    b.Property<string>("ModulAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SiraNo")
                        .HasColumnType("integer");

                    b.HasKey("ModulId");

                    b.ToTable("Moduller");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Proje", b =>
                {
                    b.Property<int>("ProjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjeId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StajyerId")
                        .HasColumnType("integer");

                    b.HasKey("ProjeId");

                    b.HasIndex("StajyerId");

                    b.ToTable("Projeler");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Referans", b =>
                {
                    b.Property<int>("ReferansId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReferansId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Eposta")
                        .HasColumnType("text");

                    b.Property<string>("Sirket")
                        .HasColumnType("text");

                    b.Property<int>("StajyerId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<string>("Unvan")
                        .HasColumnType("text");

                    b.Property<string>("Yakinlik")
                        .HasColumnType("text");

                    b.HasKey("ReferansId");

                    b.HasIndex("StajyerId");

                    b.ToTable("Referanslar");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RolId");

                    b.ToTable("Roller");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.RolModulYetki", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int>("ModulId")
                        .HasColumnType("integer");

                    b.Property<char>("Yetki")
                        .HasColumnType("character(1)");

                    b.HasKey("RolId", "ModulId");

                    b.HasIndex("ModulId");

                    b.ToTable("RolModulYetkileri");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Stajyer", b =>
                {
                    b.Property<int>("StajyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StajyerId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Bolum")
                        .HasColumnType("text");

                    b.Property<string>("Cinsiyet")
                        .HasColumnType("text");

                    b.Property<string>("DaimiAdres")
                        .HasColumnType("text");

                    b.Property<int?>("DepartmanId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("DogumTarihi")
                        .HasColumnType("date");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Eposta")
                        .HasColumnType("text");

                    b.Property<string>("FotografYolu")
                        .HasColumnType("text");

                    b.Property<decimal?>("GenelOrtalama")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("KacinciStaj")
                        .HasColumnType("smallint");

                    b.Property<int?>("MentorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("ReferanslaMiGeldi")
                        .HasColumnType("boolean");

                    b.Property<string>("Sinif")
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("StajBaslangic")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("StajBitis")
                        .HasColumnType("date");

                    b.Property<string>("StajDonemiKaldigiYer")
                        .HasColumnType("text");

                    b.Property<string>("StajKonusu")
                        .HasColumnType("text");

                    b.Property<bool?>("TekrarCalisilirMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<string>("Universite")
                        .HasColumnType("text");

                    b.Property<string>("YasadigiSehir")
                        .HasColumnType("text");

                    b.HasKey("StajyerId");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("MentorId");

                    b.ToTable("Stajyerler");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.StajyerBeceri", b =>
                {
                    b.Property<int>("StajyerId")
                        .HasColumnType("integer");

                    b.Property<int>("BeceriId")
                        .HasColumnType("integer");

                    b.Property<short?>("Seviye")
                        .HasColumnType("smallint");

                    b.HasKey("StajyerId", "BeceriId");

                    b.HasIndex("BeceriId");

                    b.ToTable("StajyerBecerileri");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Yorum", b =>
                {
                    b.Property<int>("YorumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("YorumId"));

                    b.Property<int>("StajyerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("YazanId")
                        .HasColumnType("integer");

                    b.Property<string>("YorumMetni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("YorumId");

                    b.HasIndex("StajyerId");

                    b.HasIndex("YazanId");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Beceri", b =>
                {
                    b.HasOne("StajyerTakip.Models.DbModels.BeceriKategori", "BeceriKategori")
                        .WithMany("Beceriler")
                        .HasForeignKey("BeceriKategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BeceriKategori");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Degerlendirme", b =>
                {
                    b.HasOne("StajyerTakip.Models.DbModels.Kullanici", "Degerlendiren")
                        .WithMany("Degerlendirmeler")
                        .HasForeignKey("DegerlendirenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StajyerTakip.Models.DbModels.DegerlendirmeKriteri", "Kriter")
                        .WithMany("Degerlendirmeler")
                        .HasForeignKey("KriterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StajyerTakip.Models.DbModels.Stajyer", "Stajyer")
                        .WithMany("Degerlendirmeler")
                        .HasForeignKey("StajyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Degerlendiren");

                    b.Navigation("Kriter");

                    b.Navigation("Stajyer");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Dosya", b =>
                {
                    b.HasOne("StajyerTakip.Models.DbModels.DosyaKategori", "DosyaKategori")
                        .WithMany("Dosyalar")
                        .HasForeignKey("DosyaKategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StajyerTakip.Models.DbModels.Stajyer", "Stajyer")
                        .WithMany("Dosyalar")
                        .HasForeignKey("StajyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StajyerTakip.Models.DbModels.Kullanici", "Yukleyen")
                        .WithMany("Dosyalar")
                        .HasForeignKey("YukleyenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DosyaKategori");

                    b.Navigation("Stajyer");

                    b.Navigation("Yukleyen");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Kullanici", b =>
                {
                    b.HasOne("StajyerTakip.Models.DbModels.Departman", "Departman")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StajyerTakip.Models.DbModels.Rol", "Rol")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departman");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Link", b =>
                {
                    b.HasOne("StajyerTakip.Models.DbModels.Stajyer", "Stajyer")
                        .WithMany("Linkler")
                        .HasForeignKey("StajyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stajyer");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Proje", b =>
                {
                    b.HasOne("StajyerTakip.Models.DbModels.Stajyer", "Stajyer")
                        .WithMany("Projeler")
                        .HasForeignKey("StajyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stajyer");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Referans", b =>
                {
                    b.HasOne("StajyerTakip.Models.DbModels.Stajyer", "Stajyer")
                        .WithMany("Referanslar")
                        .HasForeignKey("StajyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stajyer");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.RolModulYetki", b =>
                {
                    b.HasOne("StajyerTakip.Models.DbModels.Modul", "Modul")
                        .WithMany("RolModulYetkileri")
                        .HasForeignKey("ModulId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StajyerTakip.Models.DbModels.Rol", "Rol")
                        .WithMany("RolModulYetkileri")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modul");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Stajyer", b =>
                {
                    b.HasOne("StajyerTakip.Models.DbModels.Departman", "Departman")
                        .WithMany("Stajyerler")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StajyerTakip.Models.DbModels.Kullanici", "Mentor")
                        .WithMany("Stajyerler")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departman");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.StajyerBeceri", b =>
                {
                    b.HasOne("StajyerTakip.Models.DbModels.Beceri", "Beceri")
                        .WithMany("StajyerBecerileri")
                        .HasForeignKey("BeceriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StajyerTakip.Models.DbModels.Stajyer", "Stajyer")
                        .WithMany("StajyerBecerileri")
                        .HasForeignKey("StajyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beceri");

                    b.Navigation("Stajyer");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Yorum", b =>
                {
                    b.HasOne("StajyerTakip.Models.DbModels.Stajyer", "Stajyer")
                        .WithMany("Yorumlar")
                        .HasForeignKey("StajyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StajyerTakip.Models.DbModels.Kullanici", "Yazan")
                        .WithMany("Yorumlar")
                        .HasForeignKey("YazanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stajyer");

                    b.Navigation("Yazan");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Beceri", b =>
                {
                    b.Navigation("StajyerBecerileri");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.BeceriKategori", b =>
                {
                    b.Navigation("Beceriler");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.DegerlendirmeKriteri", b =>
                {
                    b.Navigation("Degerlendirmeler");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Departman", b =>
                {
                    b.Navigation("Kullanicilar");

                    b.Navigation("Stajyerler");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.DosyaKategori", b =>
                {
                    b.Navigation("Dosyalar");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Kullanici", b =>
                {
                    b.Navigation("Degerlendirmeler");

                    b.Navigation("Dosyalar");

                    b.Navigation("Stajyerler");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Modul", b =>
                {
                    b.Navigation("RolModulYetkileri");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Rol", b =>
                {
                    b.Navigation("Kullanicilar");

                    b.Navigation("RolModulYetkileri");
                });

            modelBuilder.Entity("StajyerTakip.Models.DbModels.Stajyer", b =>
                {
                    b.Navigation("Degerlendirmeler");

                    b.Navigation("Dosyalar");

                    b.Navigation("Linkler");

                    b.Navigation("Projeler");

                    b.Navigation("Referanslar");

                    b.Navigation("StajyerBecerileri");

                    b.Navigation("Yorumlar");
                });
#pragma warning restore 612, 618
        }
    }
}
